### ISSUE TITLE
bundle 파일 생성 에러

### ISSUE THREAD

**Issue by noolkim** [zeakd/react-naver-maps#10]
react-create-app으로 만든 상태에서

produnction env로 bundle 파일 생성 시 아래 와 같은 에러가 납니다. 

```
Failed to minify the code from this file:

        ./node_modules/react-naver-maps/dist/react-naver-maps.esm.js:78
```

위 에러 라인 찾아가 아래 코드 처럼 수정하면 잘 묶이긴 합니다.

수정전
`var _lazyUpdateKVO = _asyncToGenerator(function* (_ref) {`
수정후
`var _lazyUpdateKVO = _asyncToGenerator(function (_ref) {`

**Comment by zeakd** [comment]
@noolkim 이슈 감사합니다. 이슈를 재현할 수 있는 프로젝트 레포나, 혹은 babel, webpack  설정 및 버전을 알 수 있을까요?

**Comment by noolkim** [comment]
"webpack": "3.8.1",
"babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",

영향있는건 이정도 인듯 싶습니다.

**Comment by zeakd** [comment]
@noolkim 네 확인해본 결과 babel 빌드 과정에서 문제가 발생했던 것이 아니라, 0.0.11 버전에서 esm.js가 제대로 빌드되지 않은 채로 배포되었기 때문으로 확인되었습니다. 이 배포 이슈는 이후 버전에서 이미 해결되었으며  **latest** 버전 (0.0.12)로 **react-naver-maps**를 업데이트해서 다시 확인해주시면 감사하겠습니다. 🙏

**Comment by zeakd** [comment]
해당 버전 0.0.11은 deprecated 하겠습니다.
