### ISSUE TITLE
ncpClientId를 추가해도 "clientId is required"라는 에러가 발생합니다.

### ISSUE THREAD

**Issue by ChaeWonKong** [zeakd/react-naver-maps#11]
안녕하세요.
react-naver-maps를 이용해 개발하려고 합니다.
최근 ncp에서만 naver-maps를 이용하게 바뀌어서 그렇게 사용 중인데요.

```
<RenderAfterNavermapsLoaded ncpClientId={my_cliet_id}>
          <NaverMap id="naver_maps" style={{ width: "100%" }} height="300px" />
        </RenderAfterNavermapsLoaded>
```
위 코드처럼 작성할 경우 다음과 같은 에러가 발생합니다.
`loadNavermapsScript: clientId is required`

제 생각에 ncpClientId를 props로 추가하더라도 clientId를 required로 요구하는 것 같은데,
혹시 해결할 수 있는 방법이 있을까요?

**Comment by zeakd** [comment]
안녕하세요. 이슈 감사드립니다.
말씀하신 ncpClientId 추가문제는 #8 에서 해결되어서 오늘 중에 배포될 예정입니다. :)

**Comment by ChaeWonKong** [comment]
@zeakd 답변 감사드립니다~

**Comment by zeakd** [comment]
@ChaeWonKong 네 배포되었으니 확인 부탁드립니다 -
