### ISSUE TITLE
react-naver-maps v0.1.0~ 변경 후 컴파일 에러 문의

### ISSUE THREAD

**Issue by TaeJunKwon** [zeakd/react-naver-maps#111]
ERROR in ./src/components/TextChart.js 20:0-64
Module not found: Error: Package path ./dist/hocs-018c38ad is not exported from package /Users/***/**/build/project-front/node_modules/react-naver-maps (see exports field in /Users/***/**/build/project-front/node_modules/react-naver-maps/package.json)

ERROR in ./node_modules/react-naver-maps/dist/chunk-AAMRD6HB.mjs 9:0-40
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/***/**/build/project-front/node_modules/react-naver-maps/dist'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

"react-naver-maps": "^0.1.0" ~ 로 변경 후 발생한 에러로 해결 방법이 있을까요?

> "dependencies": {
    "@date-io/date-fns": "^2.10.8",
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.61",
    "@material-ui/pickers": "^3.3.10",
    "@material-ui/styles": "^5.0.0-alpha.33",
    "@material-ui/system": "^5.0.0-alpha.33",
    "@mui/icons-material": "^5.0.5",
    "@mui/material": "^5.2.4",
    "@mui/utils": "^5.14.13",
    "@nivo/bar": "^0.80.0",
    "@nivo/colors": "^0.80.0",
    "@nivo/core": "^0.80.0",
    "@nivo/line": "^0.80.0",
    "@nivo/pie": "^0.80.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.2",
    "axios": "^0.21.1",
    "axios-progress-bar": "^1.2.0",
    "css-loader": "^6.7.1",
    "geolocation-error-code-3": "^1.0.5",
    "jquery": "^3.6.0",
    "moment": "^2.29.1",
    "node-sass": "^7.0.1",
    "package.json": "^2.0.1",
    "parse-url": "^6.0.5",
    "postcss-loader": "^6.2.1",
    "prop-types": "^15.7.2",
    "qs": "^6.9.6",
    "query-string": "^6.14.0",
    "react": "^17.0.2",
    "react-async": "^10.0.1",
    "react-csv": "^2.0.3",
    "react-datepicker": "^3.6.0",
    "react-dom": "^17.0.2",
    "react-dropzone": "^11.3.4",
    "react-feather": "^2.0.9",
    "react-full-screen": "^1.1.0",
    "react-geolocated": "^3.1.0",
    "react-grid-layout": "^1.3.0",
    "react-helmet": "^6.1.0",
    "react-kakao-login": "^2.0.3",
    "react-loading": "^2.0.3",
    "react-medium-image-zoom": "^3.1.3",
    "react-modal": "^3.12.1",
    "react-naver-maps": "^0.1.0",
    "react-perfect-scrollbar": "^1.5.8",
    "react-redux": "^7.2.2",
    "react-responsive": "^8.2.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^5.0.0",
    "react-sizeme": "^3.0.2",
    "react-table": "^7.6.3",
    "react-toastify": "^7.0.4",
    "react-validation": "^3.0.7",
    "react-window": "^1.8.6",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-effects-geolocation": "^1.0.2",
    "redux-form": "^8.3.7",
    "redux-form-website-template": "^1.0.21",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "resolve-url-loader": "^5.0.0",
    "sass-loader": "^12.6.0",
    "useful-tools": "^0.2.6",
    "web-vitals": "^0.2.4"
  }

**Comment by zeakd** [comment]
주신 버그는 react 를 18로 버전업하면 해결될 것 같습니다. 혹은 package.json 에 type: module 이 있다면 제거해주세요
