### ISSUE TITLE
네이버지도 API 유료 정책에 따른 대응이 궁금합니다~ 

### ISSUE THREAD

**Issue by mirror-neuron** [zeakd/react-naver-maps#16]
안녕하세요, 덕분에 react에서 네이버지도를 사용하여 개발을 진행하고 있는데요.
먼저 감사드립니다!! :)

궁금한 점이 있어서요, 이번에 네이버지도 유료로 변경된다던데
기존에 개발된 것도 있고 4월 중순 이후로는 기존 사이트에서 맵자체가 깨질 것 같은데ㅠㅠ
혹시 관련되어 어떻게 진행하시고자 예정이신지 답변 부탁드려도 될까요?

**Comment by zeakd** [comment]
@mirror-neuron 안녕하세요. 라이브러리에 관심가져주셔서 감사합니다 😊 

네이버의 이번 유료화 작업은 Naver Maps Api를 기존 네이버개발자센터에서 Naver Cloud Platform 으로 옮기면서 진행이 되는데요, Naver Cloud Platform에서 클라이언트 키를 발급받아 사용하시면됩니다. 

[네이버 지도 클라이언트 키 발급](https://navermaps.github.io/maps.js.ncp/docs/tutorial-1-Getting-Client-ID.html)

이 키로 **react-naver-maps**를 사용하실 때에는 [Getting Started](https://zeakd.github.io/react-naver-maps/?id=getting-started) 에서 나와있는 것처럼, clientId 대신, ncpClientId에 발급받으신 클라이언트 키를 입력하시면 기존 NaverMaps Api와 똑같은 방식으로 사용가능합니다.  **\<RenderAfterNavermapsLoaded ncpClientId={MY_CLIENT_ID} />**를 사용하셔도 좋고, script 에 직접 ncpClientId를 넣으셔도 됩니다.

NCP로 이관된 NaverMaps는 바로 유료화가 되는 것이 아니라, 1년간 월 600만건까지는 무료로 제공하기 때문에 [**react-naver-maps Docs**](https://zeakd.github.io/react-naver-maps)는 이 무료제공을 사용하여 서비스할 예정입니다. 😃

**Comment by mirror-neuron** [comment]
상세한 답변 감사합니다 :)
