### ISSUE TITLE
InfoWindow 를 사용할 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by dioscuroi** [zeakd/react-naver-maps#17]
네이버 지도의 InfoWindow 는 어떻게 사용할 수 있을까요? 아래 예제를 구현하고 싶은데 react 에서는 어떻게 하면 되는지 여쭤보고 싶어서요;

https://navermaps.github.io/maps.js.ncp/docs/tutorial-1-infowindow-simple.example.html

좋은 라이브러리 만들어주셔서 감사합니다!!

**Comment by khchoi0301** [comment]
어떻게 처리 되었나요?? infoWindow 사용이 가능한가요?
