### ISSUE TITLE
혹시 drawing manager 라이브러리 추가일정을 알수 있을가요?

### ISSUE THREAD

**Issue by siosio34** [zeakd/react-naver-maps#21]
https://navermaps.github.io/maps.js.ncp/docs/tutorial-1-drawing-simple.example.html

해당 예제를 따라가며 진행중인데 아직 해당부분이 이 라이브러리에 반영이 안된거같아서 혹시 언제 계획이 있으신지 알수 있을가요?

**Comment by zeakd** [comment]
안녕하세요. 프로젝트에 관심가져주셔서 감사합니다. 

drawing, panorama 등의 submodule은 아직 개발계획이 없었습니다만, drawing 부분은 비교적 간단하여 원하신다면 drawing 부분부터 작업이 가능할 것을 보입니다.
다만 일정이 빠듯하여 8월말부터 시작할 수 있을것같네요.

그렇지만 꼭 제공되는 컴포넌트가 있지 않아도 본 **react-naver-maps**는 map 인스턴스를 제공하기 때문에 **componentDidMount** 안에 직접 **naver.maps.drawing.DrawingManager**를 작성하는 것이 가능합니다. 따라서 빠른 시일 내에 개발을 원하신다면 **\<NaverMap /\>** 의 ref를 통해 map 인스턴스에 직접 접근하셔서 직접 drawingManager instance를 생성하시면 가능합니다. 인스턴스에 접근하는 방식은 이 문서를 참고해주세요. [컴포넌트-인스턴스에-접근하기](https://zeakd.github.io/react-naver-maps/#/Advanced%20Guide?id=%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%EC%97%90-%EC%A0%91%EA%B7%BC%ED%95%98%EA%B8%B0)

이슈나 질문이 있으시다며면 다시 오픈해주세요. 감사합니다.

**Comment by siosio34** [comment]
![image](https://user-images.githubusercontent.com/7166022/63074765-b6bfb880-bf69-11e9-8a6f-cc90553f5c60.png)
현재 저는 이렇게 사용을 하고있는데 지금 당장 사용하고 싶으면 말씀하신것처럼 ref 로 참조해서쓰구 이런식으로 네이버맵 객체를 생성해서 드로잉매니저를 사용할려면 팔월 말정도에 시작할수 있다고 이해를 하면될가요?
