### ISSUE TITLE
drawing manager #21 대답에 대한 질문

### ISSUE THREAD

**Issue by siosio34** [zeakd/react-naver-maps#22]
![image](https://user-images.githubusercontent.com/7166022/63074765-b6bfb880-bf69-11e9-8a6f-cc90553f5c60.png)
현재 저는 이렇게 사용을 하고있는데 지금 당장 사용하고 싶으면 말씀하신것처럼 ref 로 참조해서쓰구 이런식으로 네이버맵 객체를 생성해서 드로잉매니저를 사용할려면 팔월 말정도에 시작할수 있다고 이해를 하면될가요?

_Originally posted by @siosio34 in https://github.com/zeakd/react-naver-maps/issues/21#issuecomment-521520132_

**Comment by zeakd** [comment]
@siosio34 네 ref를 사용하시려면 전달해드렸던 링크를 참조하셔서 사용하시면 됩니다. 8월말에야 제가 작업을 시작할 수 있는거라 언제까지 완료될지는 장담드리기가 어렵네요. ㅠㅠ

**Comment by siosio34** [comment]
넵 알겠습니다. 일단 ref 를 사용해서 구현해보도록 하고 이슈는 닫겠습니다 ! 감사합니다!!
