### ISSUE TITLE
간만에 글을 남여 보아요

### ISSUE THREAD

**Issue by Andrew-Woo9** [zeakd/react-naver-maps#32]
이번에 네이버에서 맵변경을 한다고 공지가 올라왔네요.
useStyleMap =  true 요 부분이 필요한거 같은데 업데이트 계획이 있으신지 해서요.
소스 기여자가 3분이 더 늘으셨네요 ㅋㅋ

**Comment by zeakd** [comment]
안녕하세요 오랜만에 뵙네요 @Andrew-Woo9 님 저도 어제 공지를 봐서 styleMap 지원을 준비중입니다. 여기 쓰레드로 진행상황 공유하겠습니다 :smiley:

**Comment by Andrew-Woo9** [comment]
@zeakd 넵 ^^ 감사합니다.  기여자가 되어야 할텐데  자꾸 사용만해서 죄송하네요 ~

**Comment by zeakd** [comment]
해당옵션은 현재 제공중이지 않은 옵션으로 Non-issue 처리하도록 하겠습니다 감사합니다 🙏 
https://www.ncloud.com/support/notice/all/738
