### ISSUE TITLE
공식문서 에러

### ISSUE THREAD

**Issue by donghoon-song** [zeakd/react-naver-maps#33]
https://zeakd.github.io/react-naver-maps/#/Overlay%20Views/Circle

React Naver Maps Style Guide 문서를 보면 Circle뿐만 아니라 다른 컴포넌트 항목에서도 "SyntaxError: Identifier 'Circle' has already been declared" 라는 오류가 반복되는데 확인해주실 수 있나요?

**Comment by zeakd** [comment]
새 Docs를 준비하면서 #65 에서 해결될 예정입니다.
