### ISSUE TITLE
이미지 타일 쏠림 문제

### ISSUE THREAD

**Issue by khchoi0301** [zeakd/react-naver-maps#37]
next js 사용하고 모달창에서 맵을 렌더하고 있습니다.
최초 모달창 오픈시에는 문제가 없으나
모달을 다시 오픈하면 맵 타일이 쏠리는 문제가 있습니다.
우측 하단에 지도 축척이 제위치에 있는걸 보면 맵 컴포넌트 위치는 문제 없는것 같고
타일만 이동된것 처럼 보입니다.
마우스를 가져가 봐도 타일 이미지 위치가 좀 틀어진 것 같고요.

어떤 문제일까요?

![image](https://user-images.githubusercontent.com/40355461/81579288-f5927a00-93e6-11ea-962d-22e99cc8500a.png)

**Comment by khchoi0301** [comment]
width를 %에서 px로 바꾸면 문제는 해결되는데.. 가변적일 때가 난감하네요

**Comment by zeakd** [comment]
안녕하세요 @khchoi0301 님. 예시코드 없이는 확인이 어렵습니다 ㅠㅠ. 재현가능한 예시코드 부탁드립니다!

**Comment by zeakd** [comment]
None Issue 로 Close하겠습니다. 문제 발생시 다시 열어주세요.
