### ISSUE TITLE
[Question] Fetch address by term

### ISSUE THREAD

**Issue by guiaramos** [zeakd/react-naver-maps#41]
Hi guys,

Is it possible to fetch address by term ?

_input_
연남장 3

_expected result_
```js
[
 {
   "address": "연남장 로컬스티치점",
   "detail": "서울특별시 서대문구 연희로 5길 22"
 },
{
   "address": "연남장 연남방앗간",
   "detail": "서울특별시 서대문구 연희로 5길 22"
 }
]
```

thanks

**Comment by zeakd** [comment]
This issue is out of scope the library is trying to handle 😢 .
Please contact to NCloud Team. https://www.ncloud.com/
