### ISSUE TITLE
mapTypeId 관련 이슈가 있습니다.

### ISSUE THREAD

**Issue by babamba** [zeakd/react-naver-maps#42]
mapTypeId propType이 number로 지정되어있으나, 
현재 네이버클라우드플랫폼에서 제공하는 상수값은 string으로 되어있습니다. 

<NaverMap 
      mapTypeId={navermaps.MapTypeId['HYBRID'] 
/>

- react-naver-maps.esm.js
NaverMap.propTypes = {
         ...
      mapTypeId: PropTypes.string
}
로 변경하니 에러가 나지않습니다.

**Comment by zeakd** [comment]
제보 감사합니다. 반영하도록 하겠습니다.

**Comment by zeakd** [comment]
v0.1 에서 픽스되었습니다.
