### ISSUE TITLE
Firefox에서 API인증이 실패했다고 나옵니다.

### ISSUE THREAD

**Issue by leedoe** [zeakd/react-naver-maps#45]
Firefox에서 잘 사용하고 있었는데

어느 순간 네이버 지도 Open API 인증이 실패했다고 나오면서 지도가 안나옵니다.

엣지나, 크롬으로 하면 잘 나오구요.

API는 클라우드 플랫폼에서 발급받아서 문제없는 키이고 다른 브라우저에서 잘 나오는 것 보면 파폭에서 버그가 있는 것 같습니다.

![image](https://user-images.githubusercontent.com/9694532/88003326-8f8d4600-cb3f-11ea-9966-f39ee1201eed.png)

**Comment by leedoe** [comment]
음 어떤 이유인지 모르겠는데 오락가락 하네요ㅠㅠ

**Comment by zeakd** [comment]
다른 업무가 많아 확인이 지연되고 있는데 재설계시 함께 체크해보겠습니다.

**Comment by zeakd** [comment]
None Issue로 Close합니다. 재발생시 다시 Open해주세요.
