### ISSUE TITLE
MarkerClustering 기능은 어떻게 적용시키면 될까요?

### ISSUE THREAD

**Issue by mugglecoder** [zeakd/react-naver-maps#53]
https://navermaps.github.io/maps.js.ncp/docs/tutorial-marker-cluster.example.html

여기에 나오는 클러스터 기능을 사용하고 싶은데 아무리 찾아봐도 없는것같아서요..혹시 방법이 있을까요?

**Comment by odh4145** [comment]
마커 클러스터 기능 업데이트 필요합니다.

**Comment by odh4145** [comment]
마커 클러스터 기능 업데이트 필요합니다.

**Comment by zeakd** [comment]
v0.1 에서 Custom Overlay 적용이 쉽도록 업데이트 되었습니다.
Cluster 적용 Example을 확인해주세요 https://zeakd.github.io/react-naver-maps/examples/marker-cluster-tutorial/
