### ISSUE TITLE
소개 업데이트가 많이 되었네요 ~ ^^

### ISSUE THREAD

**Issue by Andrew-Woo9** [zeakd/react-naver-maps#7]
초기 버전을 받아서 사이클이나 폴리곤 등의 기능이 없었던거 같은데 직접 만들어서 넣었는데 
그 기능까지 추가가 되었네요 ~ ^^ 

질문한가지 드려보아요 
초기 버젼의 문제는 아닌것 같은데 맵을 빠르게 이동하다보면
이동이 되지 않고 다시 원래 자리로 튕기듯이 돌아오는 문제가 있는데
이건 리액트의 비동기 문제인가요?
아니면 저만의 문제인지.. 
조언 좀 부탁드립니다.

**Comment by zeakd** [comment]
안녕하세요 @Andrew-Woo9 님 그 전 버전부터 써주셨군요 😃 관심가져주셔서 감사합니다.
**react-naver-maps** 는 center, zoom 같은 kvo 변수들을 controlled component처럼 써보자는 생각으로 만들었는데요, 그래서 `render`시에 `props`로 받은 center, zoom등을 그대로 렌더하려고 합니다. 그런데 이 center, zoom이 제대로 `props`로 되지 않을 경우에 지도는 이미 x1, y1으로 이동했지만 받은 props는 x2, y2일 때 받은 props로 다시 렌더하려고 하면서 튕기 듯이 돌아오게 되는 것입니다. 

따라서 **react-naver-maps**는 controlled component처럼 사용하기 위해 onCenterChanged, onZoomChanged 등을 통해서 부모의 state를 업데이트 해주는 것이 중요합니다.

혹은, props로 맵을 제어하고 싶지 않을경우 완전히 uncontrolled component처럼 취급하여 `props.defaultCenter`, `props.defaultZoom`을 사용하는 방법도 있습니다. 이들은 생성시의 center, zoom을 결정하고 이후 render에는 관여하지 않습니다. 

controlled component와 uncontrolled component 두가지 방식에 대해서는 [Getting Started](https://zeakd.github.io/react-naver-maps/#/React%20Naver%20Maps?id=getting-started)에 작성해 두었습니다. 혹시 읽으시고 이해가 안되는 부분이 있으시다면 알려주세요.

또 지금 문제가 있으신 코드 예시를 보여주시면 자세한 답변을 드릴 수 있을 것 같습니다.
