### ISSUE TITLE
React 18.2.0버전

### ISSUE THREAD

**Issue by Onseted** [zeakd/react-naver-maps#96]
오류: 
Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0-0" from react-naver-maps@0.0.13

: 상위 react 버전으로 설치가 불가한 오류가 있습니다.
force로는 설치가 가능합니다! 
혹시 업데이트가 가능할까요??

**Comment by zeakd** [comment]
#65 에서 픽스 예정입니다 🙇

**Comment by zeakd** [comment]
v0.1 에서 react 18 사용가능하도록 업데이트되었습니다.
